// <auto-generated />
namespace AzWikiLinkChecker
{
    using System.Collections.Generic;

    using Newtonsoft.Json;

    public class Account
    {
        public string Org { get; set; }
        public string Project { get; set; }

        public string Wiki { get; set; }
        public string Token { get; set; }

        [JsonIgnore]
        public string BaseUrl => $"https://dev.azure.com/{this.Org}/{this.Project}";
    }

    // Wikis
    public class Wikis
    {
        public int count { get; set; }

        [JsonProperty("value")]
        public Wiki[] items { get; set; }
    }

    // Wiki
    public class Wiki
    {
        public string id { get; set; }
        public string name { get; set; }
        public string mappedPath { get; set; }
        public string remoteUrl { get; set; }
        public string url { get; set; }
        public string version { get; set; }

        [JsonIgnore]
        public List<Page> pages { get; set; } = new List<Page>();
    }

    // Pages
    public class Pages
    {
        public int count { get; set; }

        [JsonProperty("value")]
        public Page[] items { get; set; }
    }

    public class Page
    {
        public int id { get; set; }
        public string path { get; set; }
        public string remoteUrl { get; set; }
        public string gitItemPath { get; set; }
        public string content { get; set; }
        public bool isParentPage { get; set; }
        public string url { get; set; }
        public Page[] subPages { get; set; }
    }
}
